version: '3.9'

services:

  dev:
    # command: python3 app.py
    image: wutyeeaung/a3
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: a3_python.DockerFile
    volumes:
      - ./source_code:/root/source_code
      - ./.vscode-server:/root/.vscode-server
    