version: '3'

services:
  dev:
    image: mysql_db # image name
    build: 
      context: .
      dockerfile: .DockerFile
    ports:
      - '3306:3306'
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d